/* Generated by scripts/build-lyrics-proxy.mjs - do not edit. */

var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// lyrics-proxy/src/providers/genius.js
var genius_exports = {};
__export(genius_exports, {
  get: () => get,
  resolveSongUrl: () => resolveSongUrl,
  search: () => search
});

// lyrics-proxy/src/lib/http.js
var DEFAULT_TIMEOUT_MS = 8e3;
var UpstreamError = class extends Error {
  constructor(message, status) {
    super(message);
    this.name = "UpstreamError";
    this.status = status;
  }
};
function timeoutMs(env2) {
  const value = Number(env2?.UPSTREAM_TIMEOUT_MS);
  return Number.isFinite(value) && value > 0 ? value : DEFAULT_TIMEOUT_MS;
}
async function fetchWithTimeout(url, init = {}, timeout = DEFAULT_TIMEOUT_MS) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeout);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}
async function fetchJson(url, init = {}, timeout = DEFAULT_TIMEOUT_MS) {
  const res = await fetchWithTimeout(url, init, timeout);
  if (!res.ok) {
    throw new UpstreamError(`${describe(res.status)} for ${shortUrl(url)}`, res.status);
  }
  return res.json();
}
function shortUrl(url) {
  try {
    const parsed = new URL(url);
    return `${parsed.origin}${parsed.pathname}`;
  } catch {
    return String(url);
  }
}
function describe(status) {
  return `upstream responded ${status}`;
}
var BROWSER_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";
function baseUrl(env2, key, fallback) {
  const value = env2?.[key];
  return typeof value === "string" && value.length > 0 ? value.replace(/\/+$/, "") : fallback;
}

// lyrics-proxy/src/lib/html.js
var VOID_BREAKS = /<br\s*\/?>/gi;
function decodeEntities(input) {
  if (!input.includes("&")) return input;
  return input.replace(/&#x([0-9a-f]+);/gi, (_, hex) => safeCodePoint(parseInt(hex, 16))).replace(/&#(\d+);/g, (_, dec) => safeCodePoint(parseInt(dec, 10))).replace(/&(nbsp|amp|quot|lt|gt|apos|#39);/gi, (_, name) => {
    switch (name.toLowerCase()) {
      case "nbsp":
        return " ";
      case "amp":
        return "&";
      case "quot":
        return '"';
      case "lt":
        return "<";
      case "gt":
        return ">";
      default:
        return "'";
    }
  });
}
function safeCodePoint(code) {
  if (!Number.isFinite(code) || code < 0 || code > 1114111) return "";
  try {
    return String.fromCodePoint(code);
  } catch {
    return "";
  }
}
function stripTags(fragment) {
  return decodeEntities(
    fragment.replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<style[\s\S]*?<\/style>/gi, "").replace(/<!--[\s\S]*?-->/g, "").replace(VOID_BREAKS, "\n").replace(/<[^>]*>/g, "")
  );
}
function cleanLyrics(text) {
  if (!text) return null;
  const cleaned = text.replace(/\r\n?/g, "\n").split("\n").map((line) => line.replace(/[ \t]+$/g, "")).join("\n").replace(/\n{3,}/g, "\n\n").trim();
  return cleaned.length > 0 ? cleaned : null;
}
function sliceElement(html, openTagRegex, tagName = "div", fromIndex = 0) {
  openTagRegex.lastIndex = fromIndex;
  const match = openTagRegex.exec(html);
  if (!match) return null;
  const start = match.index + match[0].length;
  const openRe = new RegExp(`<${tagName}\\b`, "gi");
  const closeRe = new RegExp(`</${tagName}\\s*>`, "gi");
  let depth = 1;
  let cursor = start;
  while (depth > 0) {
    openRe.lastIndex = cursor;
    closeRe.lastIndex = cursor;
    const nextOpen = openRe.exec(html);
    const nextClose = closeRe.exec(html);
    if (!nextClose) return html.slice(start);
    if (nextOpen && nextOpen.index < nextClose.index) {
      depth += 1;
      cursor = nextOpen.index + nextOpen[0].length;
      continue;
    }
    depth -= 1;
    if (depth === 0) return html.slice(start, nextClose.index);
    cursor = nextClose.index + nextClose[0].length;
  }
  return null;
}
function removeExcludedNodes(fragment) {
  const openRe = /<(span|div|p|a|sup|section)\b[^>]*data-exclude-from-selection="true"[^>]*>/gi;
  let result = fragment;
  let guard = 0;
  let match;
  while ((match = openRe.exec(result)) !== null && guard < 200) {
    guard += 1;
    const tagName = match[1];
    const inner = sliceElement(result, openRe, tagName, match.index);
    if (inner === null) break;
    const innerEnd = match.index + match[0].length + inner.length;
    const closeRe = new RegExp(`</${tagName}\\s*>`, "i");
    const closeMatch = closeRe.exec(result.slice(innerEnd));
    const end = closeMatch ? innerEnd + closeMatch.index + closeMatch[0].length : innerEnd;
    result = result.slice(0, match.index) + result.slice(end);
    openRe.lastIndex = 0;
  }
  return result;
}
function extractGeniusLyrics(html) {
  if (typeof html !== "string" || html.length === 0) return null;
  const legacy = sliceElement(html, /<div[^>]*class="[^"]*\blyrics\b[^"]*"[^>]*>/i);
  if (legacy) {
    const text = cleanLyrics(stripTags(legacy));
    if (text) return text;
  }
  const containerRe = /<div[^>]*data-lyrics-container="true"[^>]*>/gi;
  const sections = [];
  let match;
  while ((match = containerRe.exec(html)) !== null) {
    const inner = sliceElement(html, containerRe, "div", match.index);
    if (inner) sections.push(stripTags(removeExcludedNodes(inner)));
    containerRe.lastIndex = match.index + match[0].length;
  }
  return cleanLyrics(sections.join("\n"));
}

// lyrics-proxy/src/providers/genius.js
var DEFAULT_BASE = "https://genius.com";
async function search(params, env2) {
  const query = [params.artist, params.name].filter(Boolean).join(" ").trim();
  if (!query) return [];
  const base = baseUrl(env2, "GENIUS_BASE_URL", DEFAULT_BASE);
  const url = `${base}/api/search/song?${new URLSearchParams({ per_page: "5", q: query })}`;
  const data = await fetchJson(url, { headers: { "User-Agent": BROWSER_USER_AGENT } }, timeoutMs(env2));
  const hits = data?.response?.sections?.[0]?.hits ?? [];
  return hits.map((hit) => hit?.result).filter((song) => song && song.url).map((song) => ({
    artist: song.artist_names ?? "",
    id: song.url,
    isSync: null,
    name: song.full_title || song.title || ""
  }));
}
async function get(id, env2) {
  if (!id) return null;
  const url = resolveSongUrl(id, env2);
  if (!url) return null;
  const res = await fetchWithTimeout(
    url,
    {
      headers: {
        Accept: "text/html,application/xhtml+xml",
        "User-Agent": BROWSER_USER_AGENT
      }
    },
    timeoutMs(env2)
  );
  if (!res.ok) {
    throw new UpstreamError(`genius responded ${res.status} for the song page`, res.status);
  }
  const html = await res.text();
  return extractGeniusLyrics(html);
}
function resolveSongUrl(id, env2) {
  let parsed;
  try {
    parsed = new URL(id);
  } catch {
    return null;
  }
  const base = new URL(baseUrl(env2, "GENIUS_BASE_URL", DEFAULT_BASE));
  if (parsed.protocol !== "https:" || parsed.hostname !== base.hostname) return null;
  return parsed.toString();
}

// lyrics-proxy/src/providers/lrclib.js
var lrclib_exports = {};
__export(lrclib_exports, {
  get: () => get2,
  search: () => search2
});
var DEFAULT_BASE2 = "https://lrclib.net";
var USER_AGENT = "feishin-lyrics-worker/1.0 (https://github.com/jeffvli/feishin)";
async function search2(params, env2) {
  const { artist, name } = params;
  if (!name && !artist) return [];
  const base = baseUrl(env2, "LRCLIB_BASE_URL", DEFAULT_BASE2);
  const query = [name, artist].filter(Boolean).join(" ");
  const url = `${base}/api/search?${new URLSearchParams({ q: query })}`;
  const data = await fetchJson(url, { headers: { "User-Agent": USER_AGENT } }, timeoutMs(env2));
  if (!Array.isArray(data)) return [];
  return data.filter((song) => song && song.id != null).map((song) => ({
    artist: song.artistName ?? "",
    id: String(song.id),
    isSync: Boolean(song.syncedLyrics),
    name: song.name ?? song.trackName ?? ""
  }));
}
async function get2(id, env2) {
  if (!id) return null;
  const base = baseUrl(env2, "LRCLIB_BASE_URL", DEFAULT_BASE2);
  const url = `${base}/api/get/${encodeURIComponent(id)}`;
  const data = await fetchJson(url, { headers: { "User-Agent": USER_AGENT } }, timeoutMs(env2));
  return data?.syncedLyrics || data?.plainLyrics || null;
}

// lyrics-proxy/src/providers/netease.js
var netease_exports = {};
__export(netease_exports, {
  get: () => get3,
  mergeLyrics: () => mergeLyrics,
  search: () => search3
});
var DEFAULT_BASE3 = "https://music.163.com";
var SEARCH_LIMIT = 5;
function neteaseHeaders(extra = {}) {
  return {
    Referer: "https://music.163.com/",
    "User-Agent": BROWSER_USER_AGENT,
    ...extra
  };
}
async function cloudSearch(base, query, env2) {
  const url = `${base}/api/cloudsearch/pc`;
  const body = new URLSearchParams({
    limit: String(SEARCH_LIMIT),
    offset: "0",
    s: query,
    total: "true",
    type: "1"
  }).toString();
  const data = await fetchJson(
    url,
    {
      body,
      headers: neteaseHeaders({ "Content-Type": "application/x-www-form-urlencoded" }),
      method: "POST"
    },
    timeoutMs(env2)
  );
  return data?.result?.songs ?? [];
}
async function legacySearch(base, query, env2) {
  const params = new URLSearchParams({
    limit: String(SEARCH_LIMIT),
    offset: "0",
    s: query,
    type: "1"
  });
  const data = await fetchJson(
    `${base}/api/search/get?${params.toString()}`,
    { headers: neteaseHeaders() },
    timeoutMs(env2)
  );
  return data?.result?.songs ?? [];
}
function normalizeSong(song) {
  if (!song || song.id == null) return null;
  const artists = song.ar ?? song.artists ?? [];
  const artist = Array.isArray(artists) ? artists.map((entry) => entry?.name).filter(Boolean).join(", ") : "";
  const album = song.al ?? song.album ?? null;
  return {
    album: album?.name ?? "",
    artist,
    duration: typeof song.dt === "number" ? song.dt / 1e3 : (song.duration ?? 0) / 1e3,
    id: String(song.id),
    isSync: null,
    name: song.name ?? ""
  };
}
async function search3(params, env2) {
  const query = [params.artist, params.name].filter(Boolean).join(" ").trim();
  if (!query) return [];
  const base = baseUrl(env2, "NETEASE_BASE_URL", DEFAULT_BASE3);
  let songs = [];
  try {
    songs = await cloudSearch(base, query, env2);
  } catch {
    songs = [];
  }
  if (songs.length === 0) {
    try {
      songs = await legacySearch(base, query, env2);
    } catch {
      songs = [];
    }
  }
  return songs.map(normalizeSong).filter(Boolean);
}
async function get3(id, env2, options = {}) {
  if (!id) return null;
  const base = baseUrl(env2, "NETEASE_BASE_URL", DEFAULT_BASE3);
  const params = new URLSearchParams({ id: String(id), kv: "-1", lv: "-1", tv: "-1" });
  const url = `${base}/api/song/lyric?${params.toString()}`;
  const res = await fetchWithTimeout(url, { headers: neteaseHeaders() }, timeoutMs(env2));
  if (!res.ok) {
    throw new UpstreamError(`upstream responded ${res.status} for song/lyric`, res.status);
  }
  const data = await res.json();
  const original = data?.lrc?.lyric || null;
  if (!original) return null;
  if (!options.translate) return original;
  return mergeLyrics(original, data?.tlyric?.lyric);
}
function mergeLyrics(original, translated) {
  if (!original) return null;
  if (!translated) return original;
  const lrcLineRegex = /\[(\d{2}:\d{2}\.\d{2,3})\](.*)/;
  const translatedMap = /* @__PURE__ */ new Map();
  for (const line of translated.split("\n")) {
    const match = line.match(lrcLineRegex);
    if (!match) continue;
    const text = match[2].trim();
    if (text) translatedMap.set(match[1], text);
  }
  if (translatedMap.size === 0) return original;
  return original.split("\n").map((line) => {
    const match = line.match(lrcLineRegex);
    if (!match) return line;
    const [, timestamp, rawText] = match;
    const originalText = rawText.trim();
    const translatedText = translatedMap.get(timestamp);
    if (translatedText && originalText) {
      return [`[${timestamp}]${originalText}`, translatedText].join("_BREAK_");
    }
    return line;
  }).join("\n");
}

// lyrics-proxy/src/providers/simpmusic.js
var simpmusic_exports = {};
__export(simpmusic_exports, {
  get: () => get4,
  search: () => search4
});
var DEFAULT_BASE4 = "https://api-lyrics.simpmusic.org";
async function search4(params, env2) {
  if (!params.name) return [];
  const base = baseUrl(env2, "SIMPMUSIC_BASE_URL", DEFAULT_BASE4);
  const url = `${base}/v1/search?${new URLSearchParams({ q: params.name })}`;
  const data = await fetchJson(url, {}, timeoutMs(env2));
  const songs = data?.data;
  if (!Array.isArray(songs)) return [];
  return songs.filter((song) => song && song.videoId).map((song) => ({
    artist: song.artistName ?? "",
    id: String(song.videoId),
    isSync: Boolean(song.syncedLyrics),
    name: song.songTitle ?? ""
  }));
}
async function get4(id, env2) {
  if (!id) return null;
  const base = baseUrl(env2, "SIMPMUSIC_BASE_URL", DEFAULT_BASE4);
  const url = `${base}/v1/${encodeURIComponent(id)}`;
  const data = await fetchJson(url, {}, timeoutMs(env2));
  const first = Array.isArray(data?.data) ? data.data[0] : data?.data;
  if (!first) return null;
  return first.syncedLyrics || first.plainLyric || null;
}

// lyrics-proxy/src/providers/index.js
var PROVIDERS = {
  genius: { ...genius_exports, feishinSource: "Genius" },
  lrclib: { ...lrclib_exports, feishinSource: "lrclib.net" },
  netease: { ...netease_exports, feishinSource: "NetEase" },
  simpmusic: { ...simpmusic_exports, feishinSource: "SimpMusic" }
};
var PROVIDER_SLUGS = Object.keys(PROVIDERS).sort();
var DEFAULT_ENABLED_SOURCES = PROVIDER_SLUGS;
function resolveEnabledSources(env2) {
  const raw = env2?.ENABLED_SOURCES;
  if (typeof raw !== "string" || raw.trim() === "") return DEFAULT_ENABLED_SOURCES;
  const requested = raw.split(",").map((slug) => slug.trim().toLowerCase()).filter(Boolean);
  const enabled = PROVIDER_SLUGS.filter((slug) => requested.includes(slug));
  return enabled.length > 0 ? enabled : DEFAULT_ENABLED_SOURCES;
}

// lyrics-proxy/src/index.js
var VERSION = "1.0.0";
var DEFAULT_CACHE_TTL_SECONDS = 3600;
var MAX_CACHE_TTL_SECONDS = 86400;
function corsHeaders(env2) {
  return {
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "GET, OPTIONS",
    "Access-Control-Allow-Origin": env2?.ALLOWED_ORIGIN || "*",
    "Access-Control-Max-Age": "86400"
  };
}
function cacheTtlSeconds(env2) {
  const value = Number(env2?.CACHE_TTL_SECONDS);
  if (!Number.isFinite(value) || value < 0) return DEFAULT_CACHE_TTL_SECONDS;
  return Math.min(value, MAX_CACHE_TTL_SECONDS);
}
function json(data, { env: env2, status = 200, ttl = 0 } = {}) {
  const headers = { "Content-Type": "application/json; charset=utf-8", ...corsHeaders(env2) };
  if (ttl > 0) headers["Cache-Control"] = `public, max-age=${ttl}`;
  return new Response(JSON.stringify(data), { headers, status });
}
function getCache() {
  return typeof caches !== "undefined" && caches?.default ? caches.default : null;
}
function tagCacheStatus(response, status) {
  const headers = new Headers(response.headers);
  headers.set("X-Lyrics-Cache", status);
  return new Response(response.body, { headers, status: response.status });
}
async function withCache({ ctx, env: env2, key }, producer) {
  const ttl = cacheTtlSeconds(env2);
  const cache = getCache();
  if (!cache || ttl === 0) return tagCacheStatus(await producer(), "BYPASS");
  const cacheKey = new Request(key, { method: "GET" });
  const hit = await cache.match(cacheKey);
  if (hit) return tagCacheStatus(hit, "HIT");
  const response = await producer();
  if (response.status === 200) {
    const toStore = new Response(response.clone().body, {
      headers: new Headers(response.headers),
      status: response.status
    });
    toStore.headers.set("Cache-Control", `public, max-age=${ttl}`);
    const put = cache.put(cacheKey, toStore).catch(() => {
    });
    if (typeof ctx?.waitUntil === "function") ctx.waitUntil(put);
    else await put;
  }
  return tagCacheStatus(response, "MISS");
}
function readSearchParams(url) {
  const sp = url.searchParams;
  const rawDuration = Number(sp.get("duration"));
  const translate = ["1", "true", "yes"].includes((sp.get("translate") || "").toLowerCase());
  return {
    album: (sp.get("album") || "").trim() || void 0,
    artist: (sp.get("artist") || "").trim(),
    duration: Number.isFinite(rawDuration) && rawDuration > 0 ? rawDuration : void 0,
    name: (sp.get("name") || sp.get("track") || sp.get("q") || "").trim(),
    translate
  };
}
function badRequest(message, env2, status = 400) {
  return json({ error: message }, { env: env2, status });
}
async function handleSearch({ ctx, env: env2, request, url }) {
  const slug = (url.searchParams.get("source") || "").toLowerCase();
  if (!slug) return badRequest(`missing "source" parameter, expected one of: ${PROVIDER_SLUGS.join(", ")}`, env2);
  const provider = PROVIDERS[slug];
  if (!provider) return badRequest(`unknown source "${slug}", expected one of: ${PROVIDER_SLUGS.join(", ")}`, env2, 404);
  if (!resolveEnabledSources(env2).includes(slug)) {
    return badRequest(`source "${slug}" is disabled on this deployment`, env2, 403);
  }
  const params = readSearchParams(url);
  if (!params.name && !params.artist) {
    return badRequest('provide at least one of "name" or "artist"', env2);
  }
  return withCache({ ctx, env: env2, key: url.toString() }, async () => {
    try {
      const results = await provider.search(params, env2);
      return json(
        { results, slug, source: provider.feishinSource },
        { env: env2, ttl: cacheTtlSeconds(env2) }
      );
    } catch (error) {
      return json(
        { error: `search failed for ${slug}: ${error?.message ?? error}`, source: provider.feishinSource },
        { env: env2, status: 502 }
      );
    }
  });
}
async function handleGet({ ctx, env: env2, url }) {
  const slug = (url.searchParams.get("source") || "").toLowerCase();
  if (!slug) return badRequest(`missing "source" parameter, expected one of: ${PROVIDER_SLUGS.join(", ")}`, env2);
  const provider = PROVIDERS[slug];
  if (!provider) return badRequest(`unknown source "${slug}", expected one of: ${PROVIDER_SLUGS.join(", ")}`, env2, 404);
  if (!resolveEnabledSources(env2).includes(slug)) {
    return badRequest(`source "${slug}" is disabled on this deployment`, env2, 403);
  }
  const id = (url.searchParams.get("id") || "").trim();
  if (!id) return badRequest('missing "id" parameter', env2);
  const { translate } = readSearchParams(url);
  return withCache({ ctx, env: env2, key: url.toString() }, async () => {
    try {
      const lyrics = await provider.get(id, env2, { translate });
      return json({ id, lyrics: lyrics ?? null, slug, source: provider.feishinSource }, { env: env2, ttl: cacheTtlSeconds(env2) });
    } catch (error) {
      return json(
        { error: `lyrics lookup failed for ${slug}: ${error?.message ?? error}`, source: provider.feishinSource },
        { env: env2, status: 502 }
      );
    }
  });
}
var src_default = {
  async fetch(request, env2 = {}, ctx = {}) {
    const url = new URL(request.url);
    const path = url.pathname.replace(/\/+$/, "") || "/";
    if (request.method === "OPTIONS") {
      return new Response(null, { headers: corsHeaders(env2), status: 204 });
    }
    if (request.method !== "GET" && request.method !== "HEAD") {
      return json({ error: "method not allowed" }, { env: env2, status: 405 });
    }
    if (path === "/health") {
      return json(
        {
          cache: getCache() ? "edge" : "disabled",
          ok: true,
          service: "feishin-lyrics-worker",
          sources: resolveEnabledSources(env2),
          version: VERSION
        },
        { env: env2 }
      );
    }
    if (path === "/search") return handleSearch({ ctx, env: env2, request, url });
    if (path === "/get") return handleGet({ ctx, env: env2, url });
    if (path === "/") {
      return json(
        {
          endpoints: {
            "/get": "GET /get?source=<slug>&id=<remoteId>[&translate=1]",
            "/health": "GET /health",
            "/search": "GET /search?source=<slug>&name=&artist=&album=&duration="
          },
          service: "feishin-lyrics-worker",
          sources: resolveEnabledSources(env2).map((slug) => ({
            feishinSource: PROVIDERS[slug].feishinSource,
            slug
          })),
          version: VERSION
        },
        { env: env2 }
      );
    }
    return json({ error: "not found" }, { env: env2, status: 404 });
  }
};

// lyrics-proxy/entries/shared.js
var BASE_PATH = "/api/lyrics";
function toWorkerRequest(request) {
  const url = new URL(request.url);
  if (url.pathname === BASE_PATH) {
    url.pathname = "/";
  } else if (url.pathname.startsWith(`${BASE_PATH}/`)) {
    url.pathname = url.pathname.slice(BASE_PATH.length);
  }
  return new Request(url.toString(), request);
}
function getProcessEnv() {
  if (typeof process !== "undefined" && process && process.env) return process.env;
  return {};
}

// lyrics-proxy/entries/vercel.js
var env = getProcessEnv();
function GET(request) {
  return src_default.fetch(toWorkerRequest(request), env, {});
}
function OPTIONS(request) {
  return src_default.fetch(toWorkerRequest(request), env, {});
}
export {
  GET,
  OPTIONS
};
